---
- hosts: jdobelman.stat.rice.edu
  tasks:
  - name: Install apt Packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - sssd 
      - libpam-sss
      - libnss-sss
      - autofs 
      - cups 
      - environment-modules
      - tcsh
      - net-tools
  - name: Ensure dir cacerts exist
    file: path=/etc/ldap/cacerts state=directory
  - name: Download CA cert file
    get_url:
      url: http://qi.arc.rice.edu/sharedfiles/cacerts/fc5a8f99.0
      dest: /etc/ldap/cacerts/fc5a8f99.0
      force: yes
      mode: 0644
  - name: Remove the expired certificate
    file:
        path: /etc/ldap/cacerts/157753a5.0
        state: absent
  - name: Download autofs file to use openldap maps
    get_url:
      url: http://qi.arc.rice.edu/sharedfiles/autofs.conf
      dest: /etc/autofs.conf
      force: yes
      mode: 0644
  - name: Download ldap.conf file to use openldap maps
    get_url:
      url: http://qi.arc.rice.edu/sharedfiles/ldap-ubuntu.conf
      dest: /etc/ldap/ldap.conf
      force: yes
      mode: 0644
  - name: Download nsswitch.conf file.
    get_url:
      url: http://qi.arc.rice.edu/sharedfiles/nsswitch.conf
      dest: /etc/nsswitch.conf
      force: yes
      mode: 0644
  - name: Delete multiple files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/auto.misc
      - /etc/auto.net
      - /etc/auto.master
      - /etc/auto.home
  - name: remove files and directories
    file:
      state: "{{ item }}"
      path: "/etc/auto.master.d/"
    with_items:
      - absent
      - directory
  - name: "Download the proper sssd.conf file"
    get_url:
      url: http://qi.arc.rice.edu/sharedfiles/sssd-ubuntu.conf
      dest: /etc/sssd/sssd.conf
      force: yes
      mode: 0600
  - name: Download modulespath file
    get_url: 
      url: http://qi.arc.rice.edu/sharedfiles/modulespath
      dest: /usr/share/modules/init/.modulespath
      force: yes
      mode: 0644
  - name: Stop sssd service
    service: name=sssd state=stopped
  - name: remove files and directories
    file:
      state: "{{ item }}"
      path: "/var/lib/sss/db"
    with_items:
      - absent
      - directory
  - name: Start sssd service
    service: name=sssd state=started enabled=yes
  - name: reStart autofs service
    service: name=autofs state=restarted
