---
- hosts: one
  tasks:
  - name: Stop slapd
    service: name=slapd state=stopped
  - name: remove files and directories under /var/lib/ldap
    file:
      state: "{{ item }}"
      path: "/var/lib/ldap"
    with_items:
      - absent
      - directory
  - name: Update db
    shell: slapadd -n 2 -l /BK/ol/092120.ldif
  - name: Recursively change ownership of a directory
    file:
      path: /var/lib/ldap
      state: directory
      recurse: yes
      owner: ldap
      group: ldap
  - name: Start slapd
    service: name=slapd state=started
# one -> han.stat.rice.edu
# /BK/ol/082520.ldif was the result from ol.arc.rice.edu:~/bin/slapcat.sh
# 2 -> mdb database at han.stat.rice.edu
# Data loading was successful on 08/25/20
