- hosts: cmor2208a.caam.rice.edu
  tasks:
  - name: install prerequisite
    yum:
      name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2', 'container-selinux']
  - name: add docker-ce repo
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - name: install docker-ce
    yum: name=docker-ce state=latest
  - name: Start the service
    service: name=docker state=started enabled=yes

# tested at qi.arc.rice.edu, homer.rice.edu
#    command: subscription-manager repos --enable=rhel-7-server-extras-rpms
