- hosts: one
  gather_facts: true
  tasks:
    - name: Printing all the environment variables in Ansible
      debug:
#        msg: "{{ ansible_env }}"
#        msg: "{{  ansible_nodename.split(".")[0] | lower }}"
        msg: "{{  ansible_domain.split('.')[0] | upper }}"
