---
- hosts: cmor22
  tasks:
  - name: Import the FireEye GPG Key from a file
    rpm_key:
      state: present
      key: /tmp/buildfiles/antivirus/fireeye-key.gpg

  - name: Install FireEye Agent package
    yum:
      name: /tmp/buildfiles/antivirus/fireeye/xagt-34.28.6-1.el7.x86_64.rpm
      state: present

