---
- hosts: macready.arc.rice.edu
  tasks:
  - name: install prerequisite for docker-ce
    yum:
      name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2', 'container-selinux']
  - name: add docker-ce repo
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - name: install docker-ce
    yum: name=docker-ce state=latest
  - name: Start the docker service
    service: name=docker state=started enabled=yes
  - name: Modify docker.service
    replace:
      path: /usr/lib/systemd/system/docker.service
      regexp: '^(ExecStart=.*sock)$'
      replace: '\1 --exec-opt native.cgroupdriver=systemd'
  - name: Restart service docker, also issue daemon-reload to pick up config changes
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: yes
      name: docker
  - shell: |
      cat <<EOF > /etc/yum.repos.d/kubernetes.repo
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      EOF
  - name: install kubeadm
    yum: name=kubeadm state=latest
  - name: Start the kubelet service
    service: name=kubelet state=started enabled=yes
  - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
    shell: |
      swapoff -a
#    when: kubernetes_installed is changed
  - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'
#    when: kubernetes_installed is changed
# Only macready has a value 0, so the following shell command is necessary
  - shell: |
      echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables
  - name: Join worker nodes
    shell: |
      kubeadm join 168.7.74.150:6443 --token psotv0.uehvyeq5srzhzjun --discovery-token-ca-cert-hash sha256:68c88a0b391cbb1dd0931ff96a2819e721e8ba40fd4a8fee1792c9df08dd3a41
