---
- hosts: one
  tasks:
  - name: Stop the ypbind service
    service: name=ypbind state=stopped enabled=no
    ignore_errors: true
  - name: Install yum Packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - sssd 
      - openldap 
      - openldap-clients 
      - autofs 
      - cups 
      - nfs-utils 
      - bind-utils
      - net-tools
      - nmap
      - xclock
      - environment-modules
      - tcsh
  - name: Download sssd.conf
    get_url: 
      url: http://cassini.rice.edu/{{  ansible_domain.split('.')[0] | upper }}/sssd.conf
      dest: /etc/sssd/sssd.conf
      force: yes
      mode: 0600
  - name: Download ldap.conf
    get_url: 
      url: http://cassini.rice.edu/sharedfiles/ldap.conf
      dest: /etc/openldap/ldap.conf
      force: yes
      mode: 0644
  - name: Ensure dir cacerts exist
    file: path=/etc/openldap/cacerts state=directory
  - name: Download CA cert file
    get_url: 
      url: http://cassini.rice.edu/sharedfiles/cacerts/fc5a8f99.0
      dest: /etc/openldap/cacerts/fc5a8f99.0
      force: yes
      mode: 0644
  - name: Download cups client configuration file
    get_url: 
      url: http://cassini.rice.edu/sharedfiles/client.conf
      dest: /etc/cups/client.conf
      force: yes
      mode: 0644
  - name: Download autofs file to use openldap maps
    get_url: 
      url: http://cassini.rice.edu/sharedfiles/autofs
      dest: /etc/sysconfig/autofs
      force: yes
      mode: 0644
  - name: Download nsswitch.conf file to use openldap maps
    get_url: 
      url: http://cassini.rice.edu/sharedfiles/nsswitch.conf
      dest: /etc/nsswitch.conf
      force: yes
      mode: 0644
  - name: Start sssd service
    service: name=sssd state=restarted enabled=yes
  - name: Run authconfig
    script: /var/www/html/sharedfiles/authconfig.sh
  - name: Start autofs service
    service: name=autofs state=restarted enabled=yes
  - name: Stop NetworkManager service
    service: name=NetworkManager state=stopped enabled=no
  - name: Stop firewalld service
    service: name=firewalld state=stopped enabled=no
  - name: Disable selinux
    command: setenforce 0
  - name: Replace enforcing by permissive
    replace:
      path: /etc/sysconfig/selinux
      regexp: '[Ee]nforcing'
      replace: 'permissive'
