---
- hosts: beagle.rice.edu
  tasks:
  - name: Remove yum Packages
    yum: 
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - cuda*
      - nvida*
  - name: Install yum Packages
    yum: 
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - nvidia-driver-branch-470
      - cuda-11-4
## Has not been tested on any host
