---
- hosts: one
  tasks:
  - name: Install yum Packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - openldap-clients 
      - openldap-servers
      - openldap-devel
      - httpd
      - phpldapadmin
      - nfs-utils 
      - bind-utils
      - net-tools
      - nmap
      - certbot
      - python2-certbot-apache
  - name: Download slapd.conf
    get_url: 
      url: http://cassini.rice.edu/sharedfiles/slapd.conf
      dest: /etc/openldap/slapd.conf
      force: yes
      mode: 0644
  - name: Download config.php
    get_url: 
      url: http://cassini.rice.edu/sharedfiles/config.php
      dest: /etc/phpldapadmin/config.php
      force: yes
      mode: 0640
      owner: root
      group: apache
  - name: Download phpldapadmin.conf
    get_url:
      url: http://cassini.rice.edu/sharedfiles/phpldapadmin.conf
      dest: /etc/httpd/conf.d/phpldapadmin.conf
      force: yes
      mode: 0644
  - name: Change file ownership, group and permissions
    file:
      path: /var/log/pla_debug.log
      owner: apache
      group: apache
      mode: '0644'
  - name: Recursively change ownership of a directory
    file:
      path: /usr/share/phpldapadmin
      state: directory
      recurse: yes
      owner: apache
      group: apache
