---
- hosts: one
  gather_facts: true
  tasks:
    - name: Print the envvar in Ansible
      debug: 
        msg: "{{ lookup('env','HOME') }}"
    - name: Printing all the environment variables in Ansible
      debug:
        msg: "{{ ansible_env }}"
