---
- hosts: brpc
  tasks:
  - name: Run command
    shell: getenforce
#    shell: grep success /var/log/secure* | sed 's/.*user=//'
#    no_log: true
    args:
       warn: false # set warn=false to prevent warning
    register: getenforce

  - debug: msg="The registered variable output is {{ getenforce.rc }}"
  - debug: msg="{{ getenforce.stdout }}"
#  - debug: msg="{{ rpm.stderr }}"
  - name: Ensure SELinux is set to permissive mode when reboot
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=permissive
    when: getenforce.stdout.find('nforcing') != -1
  - name: Set to permissive mode
    shell: setenforce 0
    when: getenforce.stdout.find('nforcing') != -1
