---
- hosts: cmor2208f.caam.rice.edu
#- hosts: one
  tasks:
  - name: Import a key from a url
    ansible.builtin.rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc
  - shell: |
      cat << EOF > /etc/yum.repos.d/vscode.repo
      [code]
      name=Visual Studio Code
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
      EOF
  - name: Install yum Packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - code

