---
- hosts: three
  tasks:
  - name: Install the skyp rpm from a remote repo
    ansible.builtin.yum:
      name: 
        - http://li.nux.ro/download/nux/dextop/el7/x86_64/qtwebkit-2.3.4-6.el7.i686.rpm
        - http://download.skype.com/linux/skype-4.3.0.37-fedora.i586.rpm
      state: present
