---
- hosts: jasmine.rice.edu
  tasks:
  - name: Remove yum Packages
    yum: 
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - zabbix-agent
      - zabbix-release
  - shell: yum-config-manager --disable EI_Zabbix4-EL7_Zabbix-4-EL7
  - name: Install zabbix agent repo
#    yum: name=https://repo.zabbix.com/zabbix/5.4/rhel/7/x86_64/zabbix-release-5.4-1.el7.noarch.rpm
    yum: name=https://repo.zabbix.com/zabbix/6.2/rhel/7/x86_64/zabbix-release-6.2-1.el7.noarch.rpm
  - name: Install zabbix agent package
#    yum: name=https://repo.zabbix.com/zabbix/5.4/rhel/7/x86_64/zabbix-agent-5.4.3-1.el7.x86_64.rpm
    yum: name=https://repo.zabbix.com/zabbix/6.2/rhel/7/x86_64/zabbix-agent-6.2.1-1.el7.x86_64.rpm
  - name: Download config file
    get_url: 
      url: http://qi.arc.rice.edu/sharedfiles/zabbix_agentd.conf
      dest: /etc/zabbix/zabbix_agentd.conf
      force: yes
      mode: 0644
  - name: Start the service
    service: name=zabbix-agent state=restarted enabled=yes
  - name: Install yum Packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - iptables-services
  - name: Download iptables
    get_url: 
      url: http://qi.arc.rice.edu/sharedfiles/iptables.wkst
      dest: /etc/sysconfig/iptables
      force: yes
      mode: 0644
  - name: Open zabbix agent port 10050
    lineinfile:
       path: /etc/sysconfig/iptables
       regex: '10050'
       line: "-A RICENET -p tcp -m tcp --dport 10050 -m state --state NEW -j ACCEPT"
       backup: yes
  - name: Restart the iptables service
    service: name=iptables state=restarted enabled=yes
   
