---
- hosts: hv.caam.rice.edu
  tasks:
  - name: Remove yum Packages
    yum: 
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - zabbix-agent
      - zabbix-release
  - name: install the latest version of yum-utils
    yum:
      name: yum-utils
      state: latest
  - shell: yum-config-manager --disable EI_Zabbix4-EL8_Zabbix4-EL8
  - shell: setsebool -P httpd_can_connect_zabbix on
  - name: Import key
    ansible.builtin.rpm_key:
        state: present
        key: https://repo.zabbix.com/zabbix-official-repo.key
  - name: Install zabbix agent repo
    yum: name=https://repo.zabbix.com/zabbix/6.2/rhel/8/x86_64/zabbix-release-6.2-1.el8.noarch.rpm
  - name: Install zabbix agent package
    yum: name=https://repo.zabbix.com/zabbix/6.2/rhel/8/x86_64/zabbix-agent-6.2.1-1.el8.x86_64.rpm
  - name: Download config file
    get_url: 
      url: http://qi.arc.rice.edu/sharedfiles/zabbix_agentd.conf
      dest: /etc/zabbix/zabbix_agentd.conf
      force: yes
      mode: 0644
  - name: Start the service
    service: name=zabbix-agent state=restarted enabled=yes
#  - name: Download iptables
#    get_url: 
#      url: http://cassini.rice.edu/sharedfiles/iptables.wkst
#      dest: /etc/sysconfig/iptables
#      force: yes
#      mode: 0644
#  - name: Open zabbix agent port 10050
#    lineinfile:
#       path: /etc/sysconfig/iptables
#       regex: 10050
#       line: "-A RICENET -p tcp -m tcp --dport 10050 -m state --state NEW -j ACCEPT"
#       backup: yes
#  - name: Retart the iptables service
#    service: name=iptables state=restarted enabled=yes
   
